module Standard_types
{
    typedef int8 int8_t;
    typedef uint8 uint8_t;
    typedef int16 int16_t;
    typedef uint16 uint16_t;
    typedef int32 int32_t;
    typedef uint32 uint32_t;
    typedef boolean Boolean_t;
    typedef double Double_t;
};
